name: tests

on: [ push, pull_request ]

jobs:
  lint-and-ut:
    strategy:
      matrix:
        version: ['1.19', '1.20' ]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Golangci Lint
        # https://golangci-lint.run/
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
      - name: Unit Test
        run: go test -race ./...
